import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div className="App">
          <div className="container">
            <div className="pages">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
